addr: 127.0.0.1:18085
base_url: http://localhost:18085
exec_args: serve

default-moderator-name: Modymoody

recording:
    webdav-path: meeting-recordings
    player-base-url: "https://media.lobb.ie/"
    local-retention-days: 14
    cloudflare:
       stream-ttl-days: 90
